[Overlay]
schema-version = 1

[General]
prefer-ipv6 = false
fallback-dns-server = system
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true
dns-direct-fallback-proxy = false
udp-policy-not-supported-behaviour = REJECT
skip-proxy = www.baidu.com, yunbusiness.ccb.com, wxh.wo.cn, gate.lagou.com, www.abchina.com.cn, www.shanbay.com, login-service.mobile-bank.psbc.com, mobile-bank.psbc.com, id6.me, www.163.com
always-real-ip = easy-login.10099.com.cn, *-update.xoyocdn.com, id6.me, open.e.189.cn

[Rule]
DOMAIN,msmp.abchina.com.cn,Reject
# 自定义规则
DOMAIN-SUFFIX,ping0.cc,Proxy
DOMAIN-SUFFIX,ipdata.co,Proxy
DOMAIN-SUFFIX,b.ai,Proxy
DOMAIN-SUFFIX,kraken.com,Proxy
DOMAIN-SUFFIX,bybit-global.com,Proxy
DOMAIN-SUFFIX,bybit.com,Proxy
DOMAIN-SUFFIX,bybitglobal.com,Proxy
DOMAIN-SUFFIX,ferrigpt.asia,Proxy
DOMAIN-SUFFIX,chatgpt.com,Proxy,pre-matching,extended-matching
DOMAIN-SUFFIX,linux.do,Proxy
DOMAIN-SUFFIX,datagw-edge.alipay.com,Reject
DOMAIN-SUFFIX,adgw.alipay.com,Reject
DOMAIN-SUFFIX,tiktokv.us,Proxy
DOMAIN-SUFFIX,tiktokcdn-us.com,Proxy
DOMAIN-SUFFIX,tiktok.com,Proxy
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT
YouTube去广告 = type=http-request,pattern=^https?:\/\/.+?\.googlevideo\.com\/.+&(oad|ctier)=(?!A),script-path=https://choler.github.io/Surge/Script/YouTube.js,script-update-interval=0,enable = true

[Host]
localhost = 127.0.0.1

[URL Rewrite]

[MITM]
hostname = *.google.cn, *.googlevideo.com
enable = true
