DOMAIN,msmp.abchina.com.cn,Reject
# 自定义规则
DOMAIN-SUFFIX,ping0.cc,Proxy
DOMAIN-SUFFIX,ipdata.co,Proxy
DOMAIN-SUFFIX,b.ai,Proxy
DOMAIN-SUFFIX,kraken.com,Proxy
DOMAIN-SUFFIX,bybit-global.com,Proxy
DOMAIN-SUFFIX,bybit.com,Proxy
DOMAIN-SUFFIX,bybitglobal.com,Proxy
DOMAIN-SUFFIX,ferrigpt.asia,Proxy
DOMAIN-SUFFIX,chatgpt.com,Proxy,pre-matching,extended-matching
DOMAIN-SUFFIX,linux.do,Proxy
DOMAIN-SUFFIX,datagw-edge.alipay.com,Reject
DOMAIN-SUFFIX,adgw.alipay.com,Reject
DOMAIN-SUFFIX,tiktokv.us,Proxy
DOMAIN-SUFFIX,tiktokcdn-us.com,Proxy
DOMAIN-SUFFIX,tiktok.com,Proxy
